name = "LoveIt"
license = "MIT"
licenselink = "https://github.com/dillonzq/LoveIt/blob/master/LICENSE"
description = "A Clean, Elegant but Advanced Hugo Theme for Hugo."

homepage = "https://hugoloveit.com"
demosite = "https://hugoloveit.com"

tags = [
  "blog",
  "electronica",
  "desarrollo web",
  "programación",
  "informatica"
]
features = [
  "desarrollo web",
]

min_version = "0.62.0"

[author]
  name = "DANH"
  homepage = "https://deltronik.net"
[Base]
  name = "Dillon"
  homepage = "https://dillonzq.com/"

[original]
  name = "Fastbyte01"
  homepage = "https://www.fsb01.com/"
  repo = "https://github.com/Fastbyte01/KeepIt"
